from rdflib import URIRef

agencyClass = URIRef("http://ceosdb/class/SpaceAgency")
missionClass = URIRef("http://ceosdb/class/Mission")
instrumentClass = URIRef("http://ceosdb/class/Instrument")
measurementCategoryClass = URIRef("http://ceosdb/class/MeasurementCategory")
measurementClass = URIRef("http://ceosdb/class/Measurement")

isFromCountry = URIRef("http://ceosdb/schemas/relationship/isFromCountry")
hasFullName = URIRef("http://ceosdb/schemas/relationship/hasFullName")
builtBy = URIRef("http://ceosdb/schemas/relationship/builtBy")
hasStatus = URIRef("http://ceosdb/schemas/relationship/hasStatus")
hasLaunchDate = URIRef("http://ceosdb/schemas/relationship/hasLaunchDate")
hasEOLDate = URIRef("http://ceosdb/schemas/relationship/hasEOLDate")
hasApplications = URIRef("http://ceosdb/schemas/relationship/hasApplications")
hasOrbitType = URIRef("http://ceosdb/schemas/relationship/hasOrbitType")
hasOrbitPeriod = URIRef("http://ceosdb/schemas/relationship/hasOrbitPeriod")
hasOrbitSense = URIRef("http://ceosdb/schemas/relationship/hasOrbitSense")
hasOrbitInclination = URIRef("http://ceosdb/schemas/relationship/hasOrbitInclination")
hasOrbitAltitude = URIRef("http://ceosdb/schemas/relationship/hasOrbitAltitude")
hasOrbitLongitude = URIRef("http://ceosdb/schemas/relationship/hasOrbitLongitude")
hasOrbitLST = URIRef("http://ceosdb/schemas/relationship/hasOrbitLST")
hasRepeatCycle = URIRef("http://ceosdb/schemas/relationship/hasRepeatCycle")

hasMaturity = URIRef("http://ceosdb/schemas/relationship/hasMaturity")
isOfType = URIRef("http://ceosdb/schemas/relationship/isOfType")
hasGeometry = URIRef("http://ceosdb/schemas/relationship/hasGeometry")
hasTechnology = URIRef("http://ceosdb/schemas/relationship/hasTechnology")
samples = URIRef("http://ceosdb/schemas/relationship/samples")
hasDataAccess = URIRef("http://ceosdb/schemas/relationship/hasDataAccess")
hasDataFormat = URIRef("http://ceosdb/schemas/relationship/hasDataFormat")
hasMeasurementsSummary = URIRef("http://ceosdb/schemas/relationship/hasMeasurementsSummary")
isInMission = URIRef("http://ceosdb/schemas/relationship/isInMission")